### PR TITLE
Downgrade chrome in GitHub Actions

### PR DESCRIPTION
**Pull request by takahashim**
Fix errors in https://github.com/decidim-ice/decidim-module-decidim_awesome/actions/runs/7709307469/job/21010232676

### CODE REVIEW

**Comment by microstudi** [comment]
Hi @takahashim 

I'm implementing this solution in the 0.28 upgrade, it seems to work fine:

https://github.com/decidim/decidim/issues/12369

**Comment by takahashim** [comment]
@microstudi Thank you! I close this PR for now.

**Comment by microstudi** [comment]
oh, you can go on!
just add all the missing steps in the action and I'll merge!
the 28 upgrade is going to take some time

**Comment by takahashim** [comment]
Oh, sorry, I got your point wrong.
I'll apply the suggested workaround and if it seems to fix the issue, I'll squash the commits.

**Comment by microstudi** [comment]
Thanks @takahashim !

**Pull request merged**
